[pytest]
testpaths = tests
addopts   = -v --tb=short -q
log_cli_level = WARNING

filterwarnings =
    ignore::sqlalchemy.exc.LegacyAPIWarning
    ignore::pydantic.warnings.PydanticDeprecatedSince20
    ignore::DeprecationWarning:starlette.*
    ignore::DeprecationWarning:httpx.*
    ignore::pytest.PytestUnraisableExceptionWarning
